# Generated by Django 5.1.1 on 2024-09-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_price_alter_order_date_of_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=0.0, max_length=255),
            preserve_default=False,
        ),
    ]
